language: haskell

notifications:
  email:
    - suhailshergill@gmail.com
    - benjamin.foppa@gmail.com
  on_success: always
  on_failure: always

before_install:
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests --enable-benchmarks --with-hsc2hs=/usr/bin/hsc2hs

install:
    - cabal configure --enable-tests --enable-benchmarks -O2
    - cabal build

script:
    - cabal test --show-details=always --test-options="-a 1000 --maximum-unsuitable-generated-tests=100000 --color"
    - cabal bench || true
